server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

security.jwt.secret=messiahslittlehutundermythumb777free6769SymboliRudolfJokesBakushinMambo
security.jwt.expiration=3600000
gateway.secret=ReimuBestTouhouCharacterNoDoubtFollowMeForMoreFactsAndCreativeSecretKeysForSpringBootProjects

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://authentication-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://authentication-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**

spring.cloud.gateway.routes[2].id=client-service
spring.cloud.gateway.routes[2].uri=lb://client-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/clients/**

spring.cloud.gateway.routes[3].id=supplier-service
spring.cloud.gateway.routes[3].uri=lb://supplier-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/suppliers/**

spring.cloud.gateway.routes[4].id=catalog-service
spring.cloud.gateway.routes[4].uri=lb://catalog-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/catalog/**

spring.cloud.gateway.routes[5].id=buy-service
spring.cloud.gateway.routes[5].uri=lb://buy-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/buys/**

spring.cloud.gateway.routes[6].id=sale-service
spring.cloud.gateway.routes[6].uri=lb://sale-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/sales/**

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=false