# General config

server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://eureka-server-1:8761/eureka/
eureka.instance.prefer-ip-address=true

# Security keys

security.jwt.secret=messiahslittlehutundermythumb777free6769SymboliRudolfJokesBakushinMambo
security.jwt.expiration=3600000
gateway.secret=ReimuBestTouhouCharacterNoDoubtFollowMeForMoreFactsAndCreativeSecretKeysForSpringBootProjects
gateway.url=http://localhost:8080

# Microservices ROUTES

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://authentication-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://authentication-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**

spring.cloud.gateway.routes[2].id=client-service
spring.cloud.gateway.routes[2].uri=lb://client-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/clients/**

spring.cloud.gateway.routes[3].id=supplier-service
spring.cloud.gateway.routes[3].uri=lb://supplier-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/suppliers/**

spring.cloud.gateway.routes[4].id=catalog-service
spring.cloud.gateway.routes[4].uri=lb://catalog-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/catalog/**

spring.cloud.gateway.routes[5].id=buy-service
spring.cloud.gateway.routes[5].uri=lb://buy-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/buys/**

spring.cloud.gateway.routes[6].id=sale-service
spring.cloud.gateway.routes[6].uri=lb://sale-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/sales/**

spring.cloud.gateway.routes[7].id=foreign-supplier-service
spring.cloud.gateway.routes[7].uri=lb://supplier-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/foreignsuppliers/**

# Actuator configuration for health checks
management.endpoints.enabled-by-default=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoints.web.base-path=/actuator
management.health.diskspace.enabled=false

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[8].id=foreign-catalog-service
spring.cloud.gateway.routes[8].uri=lb://catalog-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/foreigncatalog/**

spring.cloud.gateway.routes[9].id=foreign-client-service
spring.cloud.gateway.routes[9].uri=lb://client-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/foreignclient/**

spring.cloud.gateway.routes[10].id=foreign-buy-service
spring.cloud.gateway.routes[10].uri=lb://buy-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/foreignbuy/**

# Swagger API DOCS ROUTES

spring.cloud.gateway.routes[11].id=auth-docs
spring.cloud.gateway.routes[11].uri=lb://authentication-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/auth/v3/api-docs

spring.cloud.gateway.routes[12].id=client-docs
spring.cloud.gateway.routes[12].uri=lb://client-service
spring.cloud.gateway.routes[12].predicates[0]=Path=/clients/v3/api-docs

spring.cloud.gateway.routes[13].id=supplier-docs
spring.cloud.gateway.routes[13].uri=lb://supplier-service
spring.cloud.gateway.routes[13].predicates[0]=Path=/suppliers/v3/api-docs

spring.cloud.gateway.routes[14].id=catalog-docs
spring.cloud.gateway.routes[14].uri=lb://catalog-service
spring.cloud.gateway.routes[14].predicates[0]=Path=/catalog/v3/api-docs

spring.cloud.gateway.routes[15].id=buy-docs
spring.cloud.gateway.routes[15].uri=lb://buy-service
spring.cloud.gateway.routes[15].predicates[0]=Path=/buys/v3/api-docs

# Config Swagger

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=true

springdoc.swagger-ui.urls[0].name=authentication-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=client-service
springdoc.swagger-ui.urls[1].url=/clients/v3/api-docs

springdoc.swagger-ui.urls[2].name=supplier-service
springdoc.swagger-ui.urls[2].url=/suppliers/v3/api-docs

springdoc.swagger-ui.urls[3].name=catalog-service
springdoc.swagger-ui.urls[3].url=/catalog/v3/api-docs

springdoc.swagger-ui.urls[4].name=buy-service
springdoc.swagger-ui.urls[4].url=/buys/v3/api-docs
