server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

security.jwt.secret=messiahslittlehutundermythumb777free6769SUPERSECRETKEY12345bakushinbakushin
security.jwt.expiration=3600000

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://authentication-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://authentication-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=false